name: Wisecow CI/CD pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: accuknox
  REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          echo "Docker image built: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
          docker save $REGISTRY/$IMAGE_NAME:$IMAGE_TAG -o image.tar
        
      - name: Upload image as arifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
       
  
  push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      -  name: Download image artifact
         uses: actions/download-artifact@v4
         with:
          name: docker-image
          path: .
      
      - name: Load Docker image
        run: docker load -i image.tar
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          echo "Image pushed to Docker Hub: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
  
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
      
      - name: Decode and set kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Update Image tag in deployment file
        run: |
          echo "Before Update"
          grep "image:" wisecow-k8s/deployment.yaml || true
          sed -i "s|\(image: $REGISTRY/$IMAGE_NAME:\).*|\1$IMAGE_TAG|" wisecow-k8s/deployment.yaml
          echo "After update:"
          grep "image:" wisecow-k8s/deployment.yaml
